### ISSUE TITLE
Need a bit more clarity on upload structure

### ISSUE THREAD

**Issue by vjcitn** [Bioconductor/ExperimentHub#1]
Looking at EuPathDb we see EuPathDB/GRanges/3.5/...*rda

Should we (@vjcitn, @shwetagopaul92) emulate this for restfulSEData, i.e., the final layout would be

s3://annotation-contributor/restfulSEData/rda/3.5/...*rda  (or perhaps 3.6?) ... or should
we just have a flat folder under restfulSEData with the .rda files we want to retrieve from Hub?

Thanks

**Comment by lshep** [comment]
We encourage the top directory to be the package name. The subdirectory structure is up to you. We encourage subdirectories to version if the files would be updated regularly as we would keep both old and new versions of data in the hub for reproducibility. The flat folder is fine.
