### ISSUE TITLE
old snapshot

### ISSUE THREAD

**Issue by kengcher** [Bioconductor/ExperimentHub#11]
Hi

I installed ExperimentHub but the snapshot i have is an older version:

> eh
ExperimentHub with 2049 records
# snapshotDate(): 2019-04-29 

How can i get the updated snapshot?

Thank you.

**Comment by lshep** [comment]
The snapshotDate that is given is normally determined on the version of R you are running.  If you want a more recent snapshot then you would need to update R (most likely).  To verify: What is your `sessionInfo()`

**Comment by kengcher** [comment]
Indeed, i updated bioconductor and reinstalled ExperimentHub and it's updated now. Thank you.
