### ISSUE TITLE
Misleading error message upon lack of connectivity

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/ExperimentHub#12]
Currently, we have:

https://github.com/Bioconductor/ExperimentHub/blob/9cb8394a834642a5d1f1192226d4b2ac60f946c4/R/ExperimentHub-class.R#L28

This wording suggests that the function was already using `localHub=TRUE`. I would suggest:

```
"No internet connection detected, switching to 'localHub=TRUE' instead"
```

**Comment by lshep** [comment]
Fixed in https://github.com/Bioconductor/ExperimentHub/commit/c4c9fc7cc12ed895cb572d8707dab4a1fefad286
