### ISSUE TITLE
helper function for easily removing a resource by ID

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/ExperimentHub#20]
Hi Lori, @lshep 

Perhaps it would be good to have an un/exported helper function to remove a single resource from the cache for those of us that have a corrupt cache or are doing some testing/debugging. A starting example is below based on the instructions you provided on Slack:

```r
.removeCache <- function(hubID, dry.run = TRUE) {
    eh <- ExperimentHub()
    cache <- hubCache(eh)
    bfc <- BiocFileCache(cache)
    ## query the cache to determine the BFC ID
    rid <- bfcquery(bfc, hubID)
    if (dry.run) {
        message("Resource not removed. Use 'dry.run = TRUE'")
        rid
    } else
        bfcremove(bfc, rid$rid)
}
```

**Comment by lshep** [comment]
Agreed seems useful.  Might take me a week or two to get to this but I'll look at adding asap.

**Comment by lshep** [comment]
It looks like this is already implemented through the hub class.  "removeResources"

**Comment by lshep** [comment]
Ill add it to the AnnotationHub-class and ExperimentHub class documentation

**Comment by lshep** [comment]
actually its already documented

**Comment by LiNk-NY** [comment]
Ah, sorry I missed it. Thanks for looking into it!
