### ISSUE TITLE
Error when using ExperimentHub() function

### ISSUE THREAD

**Issue by ChrisShore** [Bioconductor/ExperimentHub#21]
When I attempt to create an ExperimentHub object, I am met with the error code:

> hub <- ExperimentHub() 
Error in UseMethod("filter_") :    no applicable method for 'filter_' applied to an object of class "c('tbl_SQLiteConnection', 'tbl_dbi', 'tbl_sql', 'tbl_lazy', 'tbl')"
<br class="Apple-interchange-newline">

I am using R version 3.6.3, which I believe may be related, but if there is a workaround for this version of R (I am using a computing cluster that I am not an admin for, so updating R would be very difficult), e.g. accessing a dataset in ExperimentHub without this function, that would be very useful.

**Comment by lshep** [comment]
This has to do with the major updates dplyr / dbplyr  made a year or so ago.  Please see this thread  https://support.bioconductor.org/p/p132709/   which provides some comments on downgrading the version of dplyr / dbplyr that is installed to make the code work with the older version of R / Bioc if you are not able to upgrade to a more recent version of R/Bioc.
