### ISSUE TITLE
helper function to prioritize link over EH resource location

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/ExperimentHub#25]
Similar to Levi's suggestion, perhaps we can provide some mechanism to download from alternative remote resource locations. 
In a scenario where: 
Link1 = cloud-based / institution URL location && Link2 = EH location

We'd want to download from link1 because the submitter is already hosting the resource. 

Perhaps we could benefit by providing functionality to try to download from Link1 first and if it fails use Link2.

Do we have MD5 sums for EH resources? This would ensure that we are getting the same file from all locations.
Providers should also have MD5 sums posted somewhere as well.

**Comment by lshep** [comment]
No one has to use Bioconductor resources. You can already host on alternative servers and still be visible in the hubs.  I've said this multiple times now.

**Comment by lshep** [comment]
We have a spot in the database for mdsum.... I'll see if it's actually used it not. If not we should.
