### ISSUE TITLE
Error in ExperimentHub::ExperimentHub

### ISSUE THREAD

**Issue by LDHHAHA** [Bioconductor/ExperimentHub#26]
Hi, i run the following code:
scRNA = fix_bad_mgi_symbols(scRNA)

and met a error:

Error in ExperimentHub::ExperimentHub() : 
  DEFUNCT: As of ExperimentHub (>1.17.2), default caching location has changed.
  Problematic cache: /share/home/user/.cache/ExperimentHub
  See https://bioconductor.org/packages/devel/bioc/vignettes/ExperimentHub/inst/doc/ExperimentHub.html#default-caching-location-update

I have no ideal how to solve this problem. I hope to get your help.

**Comment by PeteHaitch** [comment]
Did you read the link to the documentation?
