### ISSUE TITLE
devel branch error ... GenomicAlignments issue?

### ISSUE THREAD

**Issue by vjcitn** [Bioconductor/ExperimentHub#30]
```
----
ERROR EVENTS:
----
checking re-building of vignette outputs ... ERROR
Error(s) in re-building vignettes:
  ...
--- re-building ‘ExperimentHub.Rmd’ using rmarkdown

Quitting from lines 141-142 [dm3] (ExperimentHub.Rmd)
Error: processing vignette 'ExperimentHub.Rmd' failed with diagnostics:
failed to load resource
  name: EH166
  title: ERR188297
  reason: require("GenomicAlignments") failed: use BiocManager::install() to install package?
--- failed re-building ‘ExperimentHub.Rmd’

SUMMARY: processing the following file failed:
  ‘ExperimentHub.Rmd’

Error: Vignette re-building failed.
Execution halted
```

**Comment by lshep** [comment]
Where are you seeing this or get this from?  I don't see this on a build report anywhere?

**Comment by mtmorgan** [comment]
hello hello I have seen this in recent R-patched. It occurs when a package is used in the vignettes, but not declared in the suggests field of the description file.

**Comment by lshep** [comment]
ah so related to the new variable declaration on the builders.  I think this is legit if you are using package data you should have the package loaded and declared appropriately.

**Comment by lshep** [comment]
what is interesting is we don't see this in release_3_17 even tho the variable is active there too

**Comment by lshep** [comment]
https://github.com/Bioconductor/ExperimentHub/commit/b24eca5e2bee701f42542b9eca51d505cd555a05
