### ISSUE TITLE
partial connectivity through authenticated proxy

### ISSUE THREAD

**Issue by delocalizer** [Bioconductor/ExperimentHub#31]
We run behind an institute firewall and we're seeing an issue with the way that ExperimentHub (or BiocFileCache underneath) has connectivity through the proxy.

Background:
* The proxy requires basic auth authentication.
* Running R 4.3.1, BiocVersion 3.17

Observations:
* Other tools including `httr::GET` succeed in reaching through when the proxy is configured. e.g. 
```
> proxy <- use_proxy(Sys.getenv('http_proxy'))
> GET("http://example.com", proxy)
Response [http://example.com/]
  Date: 2023-07-07 02:59
  Status: 200
  Content-Type: text/html; charset=UTF-8
  Size: 1.26 kB
<!doctype html>
<html>
<head>
    <title>Example Domain</title>

    <meta charset="utf-8" />
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style type="text/css">
    body {
...
```
* When constructing an ExperimentHub instance, we first use `setExperimentHubOption` to configure the proxy. The initial download of the sqlite3 db then succeeds:
```
> ExperimentHub::setExperimentHubOption("PROXY", proxy)
> eh <- ExperimentHub::ExperimentHub()
/mnt/backedup/home/my_user/.cache/R/ExperimentHub
  does not exist, create directory? (yes/no): yes
Assuming valid proxy connection through 'http://my_user:my_password@my.proxy:8080:1'
 If you experience connection issues consider using 'localHub=TRUE'
  |======================================================================| 100%
```
At this point however, we get an error returned from our proxy:
```
Error in value[[3L]](cond) : failed to connect
  reason: Received HTTP code 407 from proxy after CONNECT
  Consider rerunning with 'localHub=TRUE'
```

Additional observations:
* The `.cache/R/ExperimentHub` directory is created and populated with `BiocFileCache.sqlite  BiocFileCache.sqlite.LOCK  ae6f26910525_experimenthub.sqlite3` files
* Specifying `localHub=TRUE` yields no different result.
* Unsetting the shell environment variable `http_proxy` and manually constructing the `httr` request object  with `use_proxy(url, port =, username = , password = , auth = "basic")` : the example.com GET works fine, the initial sqlite3 db download works fine, but at the next step instead of the 407 we get:
```
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: [experimenthub.bioconductor.org] Connection timed out after 10001 milliseconds
```

Discussion:

* Setting the proxy via `setExperimentHubOption` works at least partially, otherwise we wouldn't get the sqlite3 db file downloaded
* Whatever the next step is appears to use a different mechanism to reach out. When the OS `http_proxy` environment variable is set, we get a 407 even though that proxy config works fine for other tools. When the OS `http_proxy` environment variable is unset, we get a timeout.

What could be happening here? Any insight would be much appreciated.

**Comment by lshep** [comment]
can you do a `traceback()` after invoking the error to see the code path; it might help pinpoint where it is failing.   If you use `httr::HEAD` do you have to specify the proxy to get it to work?

**Comment by delocalizer** [comment]
Thanks for spending the time on this.

Yes, our proxy is required for HEAD requests:
```
> HEAD("http://example.com")$status_code
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Failed to connect to 2606:2800:220:1:248:1893:25c8:1946: Network is unreachable
```
vs
```
> HEAD("http://example.com", proxy)$status_code
[1] 200
```

traceback shows the following when the `http_proxy` environment variable is set, and used to construct the `httr` proxy:
```
> proxy <- httr::use_proxy(Sys.getenv('http_proxy'))
> ExperimentHub::setExperimentHubOption("PROXY", proxy)
> eh <- ExperimentHub::ExperimentHub()
Assuming valid proxy connection through 'http://my_user:my_password@my_proxy:8080:1'
 If you experience connection issues consider using 'localHub=TRUE'
/mnt/backedup/home/my_user/.cache/R/ExperimentHub
  does not exist, create directory? (yes/no): yes
  |======================================================================| 100%

Error in value[[3L]](cond) : failed to connect
  reason: Received HTTP code 407 from proxy after CONNECT
  Consider rerunning with 'localHub=TRUE'
> traceback()
7: stop("failed to connect", "\n  reason: ", conditionMessage(err), 
       "\n  Consider rerunning with 'localHub=TRUE'")
6: value[[3L]](cond)
5: tryCatchOne(expr, names, parentenv, handlers[[1L]])
4: tryCatchList(expr, classes, parentenv, handlers)
3: tryCatch({
       db_date <- .restrictDateByVersion(db_path)
   }, error = function(err) {
       stop("failed to connect", "\n  reason: ", conditionMessage(err), 
           "\n  Consider rerunning with 'localHub=TRUE'")
   })
2: .Hub("ExperimentHub", hub, cache, proxy, localHub, ask, ...)
1: ExperimentHub::ExperimentHub()
```

and the following when it is unset and `httr`  is constructed manually:
```
> proxy <- httr::use_proxy("http://my_user:my_password@my_proxy:8080")
> ExperimentHub::setExperimentHubOption("PROXY", proxy)
> eh <- ExperimentHub::ExperimentHub()
Assuming valid proxy connection through 'http://my_user:my_password:my_proxy:8080:1'
 If you experience connection issues consider using 'localHub=TRUE'
/mnt/backedup/home/my_user/.cache/R/ExperimentHub
  does not exist, create directory? (yes/no): yes
  |======================================================================| 100%

Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: [experimenthub.bioconductor.org] Connection timed out after 10001 milliseconds
> traceback()
15: curl::curl_fetch_memory(url, handle = handle)
14: request_fetch.write_memory(req$output, req$url, handle)
13: request_fetch(req$output, req$url, handle)
12: request_perform(req, hu$handle$handle)
11: HEAD(link)
10: withCallingHandlers({
        HEAD(link)
    }, warning = function(w) {
        invokeRestart("muffleWarning")
    })
9: .httr_get_cache_info(fpath)
8: .util_set_cache_info(bfc, rid[ok])
7: .util_download(x, rid[i], proxy, config, "bfcadd()", ...)
6: bfcadd(bfc, rname = paste0(tolower(.class), ".sqlite3"), fpath = remote_db, 
       proxy = proxy)
5: bfcadd(bfc, rname = paste0(tolower(.class), ".sqlite3"), fpath = remote_db, 
       proxy = proxy)
4: .updateHubDB(hub_bfc, .class, url, proxy, localHub)
3: .create_cache(.class, url, cache, proxy, localHub, ask)
2: .Hub("ExperimentHub", hub, cache, proxy, localHub, ask, ...)
1: ExperimentHub::ExperimentHub()
```

**Comment by delocalizer** [comment]
I now have a workaround. If I use `httr::set_config()` to set the proxy for all requests it handles, the `ExperimentHub` construction finishes as expected. This is independent of whether the `http_proxy` environment variable is set or not:

```
> proxy <- httr::use_proxy("http://my_user:my_password@myproxy:8080")
> httr::set_config(proxy)
> ExperimentHub::setExperimentHubOption("PROXY", proxy)
> eh <- ExperimentHub::ExperimentHub()
Assuming valid proxy connection through 'http://my_user:my_password@my_proxy:8080:1'
 If you experience connection issues consider using 'localHub=TRUE'
/mnt/backedup/home/my_user/.cache/R/ExperimentHub
  does not exist, create directory? (yes/no): yes
  |======================================================================| 100%

snapshotDate(): 2023-04-24
```

and:
```
> proxy <- httr::use_proxy(Sys.getenv('http_proxy'))
> httr::set_config(proxy)
> ExperimentHub::setExperimentHubOption("PROXY", proxy)
> eh <- ExperimentHub::ExperimentHub()
Assuming valid proxy connection through 'http://my_user:my_password@my_proxy:8080:1'
 If you experience connection issues consider using 'localHub=TRUE'
/mnt/backedup/home/my_user/.cache/R/ExperimentHub
  does not exist, create directory? (yes/no): yes
  |======================================================================| 100%

snapshotDate(): 2023-04-24
```

**Comment by delocalizer** [comment]
I think I see the root of the issue from the traceback, so thanks for that suggestion. The `restrictDateByVersion` call in the `Hub` constructor [calls `biocVersionDate`](https://github.com/Bioconductor/AnnotationHub/blob/99f25849c58052a76a3647d3e714a2754da60db0/R/Hub-utils.R#L177), which [makes a `GET`](https://github.com/Bioconductor/AnnotationHub/blob/99f25849c58052a76a3647d3e714a2754da60db0/R/Hub-utils.R#L162) to https://bioconductor.org/config.yaml without using any proxy configuration. 

Since the proxy is an argument to the Hub constructor anyway, perhaps a fix is to pass it through also to `.restrictDateByVersion` and and thence `.biocVersionDate`.

Or if all Hub internet access is via `httr`,  add the proxy to the `httr` config in the Hub constructor and be done with it.

**Comment by lshep** [comment]
Thank you for looking into and reporting this as well.  I'll look into passing proxy appropriately or better documenting the work around setting the httr::use_proxy .  Much appreciated.

**Comment by delocalizer** [comment]
Thanks for maintaining this excellent package.

**Comment by lshep** [comment]
It looks like setting it globally before hand will be the simpler option because of nested functions.  I added documentation to the man pages and vignette in b950fde6082f5623d21cf3900d2fd8af0bc30fc8 as well as in the AnnotationHub and BiocFileCache as well.  I'll close the issue once the documentation changes officially propagate.  I really appreciate the extra effort on your end to help us figure this out; it was hard for me to test because I am not behind a proxy.

**Comment by lshep** [comment]
https://github.com/Bioconductor/ExperimentHub/commit/b950fde6082f5623d21cf3900d2fd8af0bc30fc8

**Comment by lshep** [comment]
@delocalizer would you by chance have time to test a new branch of BiocFileCache/ExperimentHub/AnnotationHub behind a proxy before I merge it over officially to Bioconductor?   httr is no longer being maintained and we are trying to replace with httr2.  However httr2 does not have a global proxy setting.   I could send along specific commands on how to install the testing branches and what commands to try if you are willing.  I'm limited as I'm not sure of a good way to test being behind a proxy since I don't have access to a set up.  If not no worries I can ask on other outlets for volunteers

**Comment by delocalizer** [comment]
@lshep thanks for reaching out. My new org doesn't have a proxy so I'm no longer a great test env for this — but [mitmproxy](https://docs.mitmproxy.org/stable/overview-installation/) is an excellent free tool for testing this kind of thing.  e.g. 
```bash
brew install mitmproxy
nohup mitmdump --mode regular --listen-port 8080 --proxyauth myuser:mysecret > proxy.log 2>&1 &
# correct auth
curl --proxy http://myuser:mysecret@127.0.0.1:8080 http://example.com
# incorrect auth
curl --proxy http://myuser:wrong@127.0.0.1:8080 http://example.com
```
