### ISSUE TITLE
http 409 

### ISSUE THREAD

**Issue by yyang-SDI** [Bioconductor/ExperimentHub#33]
Hi,
I am trying to get the TSS_mm10 using `TSSmm10 = hub[["EH3479"]]` and end up getting these errors:

Error: failed to load resource
  name: EH3479
  title: TSS_mm10
  reason: 1 resources failed to download
In addition: Warning messages:
1: download failed
  web resource path: 'https://experimenthub.bioconductor.org/fetch/3495'
  local file path: '/Users/yyang/Library/Caches/org.R-project.R/R/ExperimentHub/43cb7c5335c7_3495'
  reason: Conflict (HTTP 409). 
2: bfcadd() failed; resource removed
  rid: BFC32
  fpath: 'https://experimenthub.bioconductor.org/fetch/3495'
  reason: download failed 
3: download failed
  hub path: 'https://experimenthub.bioconductor.org/fetch/3495'
  cache resource: 'EH3479 : 3495'
  reason: bfcadd() failed; see warnings() 

I also tried to `wget https://experimenthub.bioconductor.org/fetch/3491` and getting this error in terminal too: 

--2023-10-17 23:04:10--  https://experimenthub.bioconductor.org/fetch/3491
Resolving experimenthub.bioconductor.org (experimenthub.bioconductor.org)... 52.73.93.102
Connecting to experimenthub.bioconductor.org (experimenthub.bioconductor.org)|52.73.93.102|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://bioconductorhubs.blob.core.windows.net/experimenthub/GenomicDistributionsData/data/chromSizes_mm10.rda [following]
--2023-10-17 23:04:11--  https://bioconductorhubs.blob.core.windows.net/experimenthub/GenomicDistributionsData/data/chromSizes_mm10.rda
Resolving bioconductorhubs.blob.core.windows.net (bioconductorhubs.blob.core.windows.net)... 20.209.52.97, 20.209.53.161, 20.60.62.97
Connecting to bioconductorhubs.blob.core.windows.net (bioconductorhubs.blob.core.windows.net)|20.209.52.97|:443... connected.
HTTP request sent, awaiting response... 409 Public access is not permitted on this storage account.
2023-10-17 23:04:11 ERROR 409: Public access is not permitted on this storage account..

Any idea how to get access to this file? 

Thanks!

**Comment by kloot** [comment]
In case it helps: Seeing the same issue for another dataset (from RStudio/Win10):
```
Warning: download failed
  web resource path: 'https://experimenthub.bioconductor.org/fetch/5388'
  local file path: 'C:\Users\KL3900X\AppData\Local/R/cache/R/ExperimentHub/67504927528e_5388'
  reason: Conflict (HTTP 409).Warning: bfcadd() failed; resource removed
  rid: BFC6
  fpath: 'https://experimenthub.bioconductor.org/fetch/5388'
  reason: download failedWarning: download failed
  hub path: 'https://experimenthub.bioconductor.org/fetch/5388'
  cache resource: 'EH5345 : 5388'
  reason: bfcadd() failed; see warnings()Error: failed to load resource
  name: EH5345
  title: Zhao immune liver counts
  reason: 1 resources failed to download
```

**Comment by lshep** [comment]
Is this the first time trying to download something from ExperimentHub or have you had success in the past?

**Comment by lshep** [comment]
This seems to be a permission error on our Microsoft Azure storage space.  We are reaching out to the Microsoft admins to get it resolved as soon as possible.  we appreciate your patience.

**Comment by yyang-SDI** [comment]
> This seems to be a permission error on our Microsoft Azure storage space. We are reaching out to the Microsoft admins to get it resolved as soon as possible. we appreciate your patience.

Thank you, and to your previous comment: it worked in the past and something just came up yesterday.

**Comment by MikeOrman** [comment]
Also having the same issue loading a dataset:

Error: failed to load resource
  name: EH8002
  title: taylor_cna.gistic_20230215
  reason: 1 resources failed to download
In addition: Warning messages:
1: download failed
  web resource path: ‘https://experimenthub.bioconductor.org/fetch/8052’
  local file path: ‘/Users/mikeorman/Library/Caches/org.R-project.R/R/ExperimentHub/3ef1fbef144_8052’
  reason: Conflict (HTTP 409).

**Comment by lshep** [comment]
Yes it will affect any resource that is hosted on microsoft azure right now.  We are working on resolving the permission issues.

**Comment by snowpong** [comment]
Are there workarounds we can use in the meantime? Other mirrors we could point to or something?

**Comment by yyang-SDI** [comment]
@kkupkova suggested to build from FASTA and GTF if you're using it for GenomicsDistributions and it worked for me
https://github.com/databio/GenomicDistributionsData/issues/9#issuecomment-1767570301

**Comment by snowpong** [comment]
Thanks  for the suggestion @yyang-SDI but it won't help in my case. I'm trying to download data needed for SeSAMe with [sesameDataCache()](https://bioconductor.org/packages/release/data/experiment/vignettes/sesameData/inst/doc/sesameData.html#Local_caching).

**Comment by snowpong** [comment]
It seems to be somewhat working now. Running sesameDataCache() it does downloads files successfully via ExperimentHub but some I get HTTP 500 (internal server error) on. Re-starting the download succeeds on 2nd try.
```
> sesameDataCache()
Metadata (N=91):

(1/91) EH8066:

  |======================================================================| 100%
(2/91) EH8067:

  |======================================================================| 100%
ExperimentHub Caching fails:
1 resources failed to downloadWarning messages:
1: download failed
  web resource path: ‘https://experimenthub.bioconductor.org/fetch/8117’
  local file path: ‘/home/espenr/.cache/R/ExperimentHub/aace34ec9672c_8117’
  reason: Internal Server Error (HTTP 500).
2: bfcadd() failed; resource removed
  rid: BFC21
  fpath: ‘https://experimenthub.bioconductor.org/fetch/8117’
  reason: download failed
3: download failed
  hub path: ‘https://experimenthub.bioconductor.org/fetch/8117’
  cache resource: ‘EH8067 : 8117’
  reason: bfcadd() failed; see warnings()
> sesameDataCache()
Metadata (N=90):

(1/90) EH8067:

  |======================================================================| 100%
(2/90) EH8068:

  |======================================================================| 100%
``` 
_Update_: sesameDataCache() successfully downloaded all it needed from ExperimentHub. Issue seems resolved.

**Comment by lshep** [comment]
It might have been latent pushing all the permissions back to files.   Thanks for letting us know.
