### ISSUE TITLE
Cannot connect to ExperimentHub server

### ISSUE THREAD

**Issue by qingbinzhou** [Bioconductor/ExperimentHub#36]
> hub <- ExperimentHub()
Cannot connect to ExperimentHub server, using 'localHub=TRUE' instead
Using 'localHub=TRUE'
  If offline, please also see BiocManager vignette section on offline use
Error in `collect()`:
! Failed to collect lazy table.
Caused by error in `db_collect()`:
! Arguments in `...` must be used.
✖ Problematic argument:
• ..1 = Inf
ℹ Did you misspell an argument name?
Backtrace:
  1. ExperimentHub::ExperimentHub()
 12. dbplyr:::collect.tbl_sql(., Inf)
 17. dbplyr::db_collect(x$src$con, sql, n = n, warn_incomplete = warn_incomplete, ...)

**Comment by lshep** [comment]
What is your `sessionInfo()`  I believe this should have been resolved if you update to the recent versions of the packages. See https://github.com/Bioconductor/BiocFileCache/pull/50  (BiocFileCache is which the ExperimentHub cache is built on)
