### ISSUE TITLE
ExperimentHub function error

### ISSUE THREAD

**Issue by zdq0808** [Bioconductor/ExperimentHub#40]
> eh <- ExperimentHub::ExperimentHub(update = TRUE)
Error in `collect()`:
! Failed to collect lazy table.
Caused by error in `db_collect()`:
! Arguments in `...` must be used.
✖ Problematic argument:
• ..1 = Inf
ℹ Did you misspell an argument name?
Run `rlang::last_trace()` to see where the error occurred.

**Comment by LiNk-NY** [comment]
Hi @DongqiangZeng0808 
It is hard to tell without a full `sessionInfo()`. 
Make sure that `BiocManager::valid()` returns `TRUE`. 
You can also try to downgrade the possibly problematic package with: 
```
devtools::install_version("dbplyr", version = "2.3.4")
```
Best,
Marcel

**Comment by lshep** [comment]
https://github.com/Bioconductor/ExperimentHub/issues/35
