### ISSUE TITLE
 resources failed to download when building package 

### ISSUE THREAD

**Issue by whtns** [Bioconductor/ExperimentHub#43]
Hi, not sure if this is the same issue as #34. I triggered a rebuild of my package chevreuldata which was built successfully on version 0.99.9 but which now fails with version 0.99.10. The data is hosted on my own server rather than azure as in #34. 

Here are the two build logs
v 0.99.9: https://bioconductor.org/spb_reports/chevreuldata_buildreport_20240805180453.html

v 0.99.10: https://bioconductor.org/spb_reports/chevreuldata_buildreport_20240813153019.html

should I ask this question in a different forum? on the package submission thread?

**Comment by lshep** [comment]
Could there have been a temporary connection or firewall condition on where you are hosting the data? I just tried locally and everything is working fine.

**Comment by lshep** [comment]
Its probably best to discuss within the contribution issue itself?  I also saw on slack that the accompanied software package needs to be reset on our system but had not heard back if it was in a set / stable place to do the reset.
