### ISSUE TITLE
failed to connect / reason: Scanner error: mapping values are not allowed in this context at line 4, column 22

### ISSUE THREAD

**Issue by nebetbastet** [Bioconductor/ExperimentHub#9]
Hello,

I meet a problem with the function ExperimentHub() (that I use with the package SingleR):

> Error in value[[3L]](cond) : failed to connect
>   reason: Scanner error: mapping values are not allowed in this context at line 4, column 22
>   Consider rerunning with 'localHub=TRUE'

My R session is:

> R version 3.6.2 (2019-12-12)
> Platform: i386-w64-mingw32/i386 (32-bit)
> Running under: Windows 10 x64 (build 18363)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252   
> [3] LC_MONETARY=French_France.1252 LC_NUMERIC=C                  
> [5] LC_TIME=French_France.1252    
> 
> attached base packages:
> [1] parallel  stats4    stats     graphics  grDevices utils     datasets 
> [8] methods   base     
> 
> other attached packages:
>  [1] DBI_1.1.0                   AnnotationDbi_1.48.0       
>  [3] dplyr_0.8.3                 ExperimentHub_1.12.0       
>  [5] AnnotationHub_2.18.0        BiocFileCache_1.10.2       
>  [7] dbplyr_1.4.2                SingleR_1.0.5              
>  [9] SummarizedExperiment_1.16.1 DelayedArray_0.12.2        
> [11] BiocParallel_1.20.1         matrixStats_0.55.0         
> [13] Biobase_2.46.0              GenomicRanges_1.38.0       
> [15] GenomeInfoDb_1.22.0         IRanges_2.20.2             
> [17] S4Vectors_0.24.2            BiocGenerics_0.32.0        
> 
> loaded via a namespace (and not attached):
>  [1] magrittr_1.5                  vctrs_0.2.1                  
>  [3] zlibbioc_1.32.0               DelayedMatrixStats_1.8.0     
>  [5] memoise_1.1.0                 RCurl_1.95-4.12              
>  [7] XVector_0.26.0                pillar_1.4.3                 
>  [9] BiocVersion_3.10.1            htmltools_0.4.0              
> [11] curl_4.3                      later_1.0.0                  
> [13] BiocNeighbors_1.4.1           lattice_0.20-38              
> [15] bit_1.1-14                    tidyselect_0.2.5             
> [17] mime_0.8                      pkgconfig_2.0.3              
> [19] Matrix_1.2-18                 fastmap_1.0.1                
> [21] R6_2.4.1                      GenomeInfoDbData_1.2.2       
> [23] shiny_1.4.0                   digest_0.6.23                
> [25] yaml_2.2.0                    RSQLite_2.2.0                
> [27] tibble_2.1.3                  httr_1.4.1                   
> [29] compiler_3.6.2                BiocManager_1.30.10          
> [31] bit64_0.9-7                   backports_1.1.5              
> [33] xtable_1.8-4                  Rcpp_1.0.3                   
> [35] zeallot_0.1.0                 rappdirs_0.3.1               
> [37] assertthat_0.2.1              blob_1.2.0                   
> [39] tools_3.6.2                   bitops_1.0-6                 
> [41] interactiveDisplayBase_1.24.0 httpuv_1.5.2                 
> [43] crayon_1.3.4                  glue_1.3.1                   
> [45] purrr_0.3.3                   rlang_0.4.2                  
> [47] promises_1.1.0                grid_3.6.2  

Thank you in advance for your help!

**Comment by nebetbastet** [comment]
I think I could find where the problem come from.

It's in the function .biocVersionDate (AnnotationHub), here:

>  yaml <- httr::content(GET("http://bioconductor.org/config.yaml"),
>                     encoding="UTF-8", as="text")
>     obj <- yaml.load(yaml)

the "yaml" object seems to have a problem

**Comment by nebetbastet** [comment]
Finally, I could solve the problem by changing "http" by "https".

I guess it's because of a security restriction of the company where I work

**Comment by lshep** [comment]
Thank you.  It is better to have "https".  I will update the code to reflect this. Thank you for reporting and investigating.

**Comment by lshep** [comment]
https://github.com/Bioconductor/AnnotationHub/commit/b74e310d529fa009fe8b349114ae54b65d8fcd8c

Updated.
